"""Prepare a program folder: bug-bounty/<slug>/SCOPE.md (+ targets.txt) from the stored Immunefi record.

The layout mirrors existing program folders (e.g. bug-bounty/livepeer/SCOPE.md). It never overwrites a
SCOPE.md you already have: that file collects hand-written rejection rules and notes.
"""

from __future__ import annotations

import os
import re
import shutil
import sqlite3
from datetime import datetime
from pathlib import Path

from . import query
from .query import ASSET_TYPES
from .util import now_utc, parse_ts
from .view import site_url, to_text

DEFAULT_ROOT = Path(os.environ.get("IW_PROGRAMS_DIR", Path(__file__).resolve().parents[2]))

_SEV = ["critical", "high", "medium", "low"]
_TYPE_TITLE = {"smart_contract": "Smart contract", "websites_and_applications": "Websites and applications",
               "blockchain_dlt": "Blockchain / DLT"}


def folder_name(slug: str) -> str:
    return re.sub(r"[^a-z0-9._-]+", "-", slug.lower()).strip("-.") or "program"


def usd(n) -> str:
    try:
        return f"${float(n):,.0f}"
    except (TypeError, ValueError):
        return "-"


def _date(s) -> str:
    dt = parse_ts(s) if isinstance(s, str) else None
    return f"{dt:%Y-%m-%d}" if dt else "?"


def _block(title: str, body) -> str:
    txt = to_text(body).strip()
    return f"### {title}\n\n{txt}\n\n" if txt else ""


def _tiers(d: dict) -> list[str]:
    """One line per severity: range across asset types plus the reward model."""
    by: dict[str, list] = {}
    for r in d.get("rewards") or []:
        by.setdefault(r.get("severity"), []).append(r)
    out = []
    for sev in _SEV:
        rs = by.get(sev)
        if not rs:
            continue
        lo = min((r.get("minReward") or 0) for r in rs)
        hi = max((r.get("maxReward") or 0) for r in rs)
        pct = {r.get("rewardCalculationPercentage") for r in rs if r.get("rewardCalculationPercentage")}
        models = {r.get("rewardModel") for r in rs if r.get("rewardModel")}
        rng = "amount in reward details" if hi == 0 else usd(hi) if lo == hi else f"{usd(lo)} to {usd(hi)}"
        extra = f" ({'/'.join(f'{p}%' for p in sorted(pct))} of funds at risk)" if pct else ""
        out.append(f"{sev.capitalize()} {rng}{extra}" + (f" [{', '.join(sorted(models))}]" if models and not pct else ""))
    return out


def render(p: query.Prog, d: dict) -> str:
    now = now_utc()
    L: list[str] = []
    a = L.append
    a(f"# {p.name} - Immunefi Bug Bounty Program\n")
    a(f"Provenance: program data pulled from the Immunefi public API on {now:%Y-%m-%d} "
      f"(`/public-api/bounty/{p.slug}/`, {len(p.assets)} asset{'s' if len(p.assets) != 1 else ''}). Verify against {site_url(p.slug)} "
      f"before submitting, programs shift. Generated by immunefi-watcher.\n")

    # ---- facts
    a("## Program facts\n")
    a(f"- Live since {_date(d.get('launchDate'))}; record last updated {_date(d.get('updatedDate'))}. "
      f"{'**PAUSED**' if p.paused else 'Not paused'}, {'**invite only**' if p.invite else 'not invite-only'}. "
      f"{'**KYC required for payouts.**' if p.kyc else 'KYC not required.'}")
    a(f"- **Max bounty: {usd(p.max_bounty)}.** Rewards in {d.get('rewardsToken') or 'unspecified token'}."
      f" Payout wallet type: {d.get('primaryPaymentWallet') or 'unspecified'}.")
    tiers = _tiers(d)
    if tiers:
        a("- Tiers: " + " / ".join(tiers))
    a(f"- **10% economic rule: {'YES' if d.get('tenPercentEconomicRule') else 'no'}**")
    poc = d.get("pocPerTypeAndSeverity") or []
    a("- PoC required for: " + (", ".join(poc) if poc else "not stated in the record (check the program page)"))
    a(f"- **Paid submission (\"Pay to Submit\"): {'YES' if p.paid_submission else 'no, free to submit'}.**")
    if p.features:
        a("- Immunefi features: " + ", ".join(p.features))
    if p.total_pool:
        a("- Prize pools: " + ", ".join(f"{k} {v:,.0f}" for k, v in p.pools.items() if v)
          + f" {p.rewards_token}")
    a("- Language: " + (", ".join(p.languages) or "n/a") + "; ecosystem: " + (", ".join(p.ecosystems) or "n/a")
      + "; type: " + (", ".join(p.project_types + p.program_types) or "n/a"))
    if p.std:
        a("- Immunefi Standard program.")
    if p.has_web:
        a("- Also has a web/app program with separate payouts. It is intentionally not included in this file.")
    for k, label in (("websiteUrl", "Website"), ("githubUrl", "GitHub")):
        if d.get(k):
            a(f"- {label}: {d[k]}")
    if d.get("endDate"):
        a(f"- Ends: {_date(d['endDate'])}")
    a("")

    ov = to_text(d.get("programOverview") or d.get("description")).strip()
    if ov:
        a("## Overview\n")
        a(ov + "\n")

    # ---- assets
    a("## Assets in scope\n")
    recent = now.timestamp() - 30 * 86400
    a(f"{len(p.assets)} asset{'s' if len(p.assets) != 1 else ''}. Entries marked **NEW** were added to scope in the last 30 days.\n")
    groups: dict[str, list] = {}
    for x in p.assets:
        groups.setdefault(x.type, []).append(x)
    for typ in [t for t in _TYPE_TITLE if t in groups] + [t for t in groups if t not in _TYPE_TITLE]:
        items = sorted(groups[typ], key=lambda x: x.when.timestamp() if x.when else 0, reverse=True)
        a(f"### {_TYPE_TITLE.get(typ, typ)} ({len(items)})\n")
        for x in items:
            new = x.when is not None and x.when.timestamp() >= recent
            note = f" - {x.description.strip()}" if x.description and x.description.strip() else ""
            when = f" (added {x.when:%Y-%m-%d})" if x.when else ""
            a(f"- {x.url}{note}{when}" + (" **NEW**" if new else ""))
        a("")
    body = to_text(d.get("assetsBodyV2")).strip()
    if body:
        a("### Notes on assets\n")
        a(body + "\n")

    # ---- rewards
    a("## Rewards\n")
    rew = d.get("rewards") or []
    if rew:
        a("| Severity | Asset type | Min | Max | Model |")
        a("|---|---|---|---|---|")
        order = {s: i for i, s in enumerate(_SEV)}
        for r in sorted(rew, key=lambda r: (order.get(r.get("severity"), 9), str(r.get("assetType")))):
            model = r.get("rewardModel") or ""
            if r.get("rewardCalculationPercentage"):
                model += f" ({r['rewardCalculationPercentage']}%)"
            fixed = model.startswith("fixed") and not r.get("minReward") and not r.get("maxReward")
            a(f"| {r.get('severity', '')} | {_TYPE_TITLE.get(r.get('assetType'), r.get('assetType') or '')} | "
              f"{usd(r.get('minReward'))} | {'fixed, amount in program rules' if fixed else usd(r.get('maxReward'))} | {model} |")
        a("")
    a(_block("Reward details", d.get("rewardsBody")).rstrip() + "\n" if d.get("rewardsBody") else "")

    # ---- impacts
    imps = d.get("impacts") or []
    a("## Impacts in scope\n")
    if imps:
        for typ in sorted({i.get("type") for i in imps}, key=lambda t: str(t)):
            for sev in _SEV:
                rows = [i for i in imps if i.get("type") == typ and i.get("severity") == sev]
                if rows:
                    a(f"{_TYPE_TITLE.get(typ, typ)} - {sev.capitalize()}:")
                    for i in rows:
                        a(f"- {i.get('title', '').strip()}")
                    a("")
    else:
        a("(none listed in the API record)\n")
    a(_block("Impact notes", d.get("impactsBody")).rstrip() + "\n" if d.get("impactsBody") else "")
    a(_block("Prioritized vulnerabilities", d.get("prioritizedVulnerabilities")).rstrip() + "\n"
      if d.get("prioritizedVulnerabilities") else "")

    # ---- out of scope / rules
    a("## Out of scope\n")
    oos = ""
    oos += _block("Program rules and exclusions", d.get("outOfScopeAndRules"))
    oos += _block("Program-specific exclusions", d.get("customOutOfScopeInformation"))
    for k, t in (("defaultOutOfScopeGeneral", "Default exclusions: general"),
                 ("defaultOutOfScopeSmartContract", "Default exclusions: smart contracts"),
                 ("defaultOutOfScopeWebAndApplications", "Default exclusions: web and applications"),
                 ("defaultOutOfScopeBlockchain", "Default exclusions: blockchain")):
        oos += _block(t, d.get(k))
    oos += _block("Prohibited activities", d.get("customProhibitedActivities") or d.get("defaultProhibitedActivities"))
    oos += _block("Feasibility limitations", d.get("defaultFeasibilityLimitations"))
    a(oos.rstrip() + "\n" if oos else "(none listed in the API record)\n")

    a("## Rules\n")
    a("- Standard Immunefi rules apply." + (" KYC required for payouts." if p.kyc else ""))
    elig = d.get("eligibilityCriteria") or []
    if elig:
        a("- Not eligible: " + ", ".join(str(e).replace("_", " ") for e in elig))
    a("")

    # ---- known issues / audits
    ki = d.get("knownIssues") or []
    a(f"## Known issues ({len(ki)})\n")
    if ki:
        for k in ki:
            a(f"- {k.get('link') or '(no link)'}")
            desc = to_text(k.get("description")).strip()
            if desc:
                a("  " + desc.replace("\n", "\n  "))
        a("")
    else:
        a("None listed in the API record. Check the program's GitHub issues and disclosed reports before submitting.\n")
    au = d.get("audits") or []
    a(f"## Audits ({len(au)})\n")
    if au:
        for x in sorted(au, key=lambda x: x.get("date") or "", reverse=True):
            a(f"- {_date(x.get('date'))} {x.get('auditor') or 'unknown'}: {x.get('url') or ''}")
        a("")
    else:
        a("None listed.\n")

    # ---- economics (machine-readable, same keys as other program folders)
    launch = parse_ts(d.get("launchDate"))
    pays_crit = any((r.get("severity") == "critical" and (r.get("maxReward") or 0) > 0) for r in rew)
    a("## Economics\n")
    a(f"max_payout_usd: {int(p.max_bounty)}")
    a(f"audit_count: {len(au)}")
    a(f"days_since_listing: {(now - launch).days if launch else 'unknown'}")
    a("fork_of: none")
    a(f"pays_criticals: {'true' if pays_crit else 'false'}")
    a(f"pay_to_submit: {'true' if p.paid_submission else 'false'}")
    return "\n".join(L).rstrip() + "\n"


def prepare(conn: sqlite3.Connection, slug: str, root: Path | None = None, mode: str = "auto") -> dict:
    """Create <root>/<slug>/ with SCOPE.md and targets.txt.

    mode "auto":      write SCOPE.md only if it does not exist (never overwrites).
    mode "new":       if SCOPE.md exists, write SCOPE.new.md beside it instead.
    mode "overwrite": replace SCOPE.md after saving the old one as SCOPE.md.bak-<timestamp>.
    """
    if mode not in ("auto", "new", "overwrite"):
        raise ValueError(f"bad mode {mode!r}")
    root = Path(root or DEFAULT_ROOT)
    progs = [x for x in query.load_programs(conn, include_removed=True) if x.slug == slug]
    if not progs:
        raise ValueError(f"unknown program {slug!r}")
    p = progs[0]
    d = query.program_data(conn, slug)
    folder = root / folder_name(slug)
    scope = folder / "SCOPE.md"
    res = {"slug": slug, "folder": str(folder), "created_folder": not folder.exists(), "wrote": None,
           "backup": None, "scope_existed": scope.exists(), "files": [], "assets": len(p.assets),
           "impacts": len(d.get("impacts") or []), "known_issues": len(d.get("knownIssues") or [])}
    folder.mkdir(parents=True, exist_ok=True)

    text = render(p, d)
    if not scope.exists():
        scope.write_text(text, encoding="utf-8")
        res["wrote"] = str(scope)
    elif mode == "new":
        alt = folder / "SCOPE.new.md"
        alt.write_text(text, encoding="utf-8")
        res["wrote"] = str(alt)
    elif mode == "overwrite":
        bak = folder / f"SCOPE.md.bak-{now_utc():%Y%m%d-%H%M%S}"
        shutil.copy2(scope, bak)  # copy first, so a failed write cannot lose the original
        res["backup"] = str(bak)
        scope.write_text(text, encoding="utf-8")
        res["wrote"] = str(scope)
    targets = folder / "targets.txt"
    if not targets.exists():
        targets.write_text("# Targets for this program. One path per line; blank lines and # comments are ignored.\n"
                           "# The program folder itself, the one holding the scope document.\n"
                           f"{folder}\n", encoding="utf-8")
        res["files"].append(str(targets))
    if res["wrote"]:
        res["files"].insert(0, res["wrote"])
    return res


def status(conn: sqlite3.Connection, slug: str, root: Path | None = None) -> dict:
    folder = Path(root or DEFAULT_ROOT) / folder_name(slug)
    scope = folder / "SCOPE.md"
    info = {"folder": str(folder), "folder_exists": folder.exists(), "scope_exists": scope.exists(),
            "scope_path": str(scope), "scope_bytes": 0, "scope_lines": 0, "scope_modified": None}
    if scope.exists():
        st = scope.stat()
        info["scope_bytes"] = st.st_size
        info["scope_lines"] = scope.read_text(encoding="utf-8", errors="replace").count("\n")
        info["scope_modified"] = datetime.fromtimestamp(st.st_mtime)
    return info
